# Generated by Django 3.1.3 on 2020-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartomante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cartomante', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('tipo_cartomante', models.CharField(max_length=200)),
                ('conceito_cartomante', models.CharField(max_length=200)),
            ],
        ),
    ]
