# Generated by Django 3.1.3 on 2020-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysticareaapp', '0002_auto_20201130_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartomante',
            name='desc_cartomante',
            field=models.TextField(default='prevalores', max_length=200),
            preserve_default=False,
        ),
    ]
